version: '3.8'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  flask:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - my-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/myDatabase

  react:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - flask
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongo-data:
